export const ACTIVITIES_FETCH_RESET = 'ACTIVITIES_FETCH_RESET';
export const ACTIVITIES_FETCH_REQUEST = 'ACTIVITIES_FETCH_REQUEST';
export const ACTIVITIES_FETCH_SUCCESS = 'ACTIVITIES_FETCH_SUCCESS';
export const ACTIVITIES_FETCH_ERROR = 'ACTIVITIES_FETCH_ERROR';
export const ACTIVITIES_FETCH_ERROR_RESET = 'ACTIVITIES_FETCH_ERROR_RESET';

export const ACTIVITIES_SEARCH_SUCCESS = 'ACTIVITIES_SEARCH_SUCCESS';

export const ACTIVITY_ADD_RESET = 'ACTIVITY_ADD_RESET';
export const ACTIVITY_ADD_REQUEST = 'ACTIVITY_ADD_REQUEST';
export const ACTIVITY_ADD_SUCCESS = 'ACTIVITY_ADD_SUCCESS';
export const ACTIVITY_ADD_ERROR = 'ACTIVITY_ADD_ERROR';


export const ACTIVITY_UPDATE_RESET = 'ACTIVITY_UPDATE_RESET';
export const ACTIVITY_UPDATE_REQUEST = 'ACTIVITY_UPDATE_REQUEST';
export const ACTIVITY_UPDATE_SUCCESS = 'ACTIVITY_UPDATE_SUCCESS';
export const ACTIVITY_UPDATE_ERROR = 'ACTIVITY_UPDATE_ERROR';


export const ACTIVITY_DELETE_RESET = 'ACTIVITY_DELETE_RESET';
export const ACTIVITY_DELETE_REQUEST = 'ACTIVITY_DELETE_REQUEST';
export const ACTIVITY_DELETE_SUCCESS = 'ACTIVITY_DELETE_SUCCESS';
export const ACTIVITY_DELETE_ERROR = 'ACTIVITY_DELETE_ERROR';
