export const AUTH_RESET = 'AUTH_RESET';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_STATUS = 'AUTH_STATUS';
export const AUTH_RESET_ERROR = 'AUTH_RESET_ERROR';


export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_RESET = 'LOGIN_RESET';

export const LOGIN_ACTION_REQUEST = 'LOGIN_ACTION_REQUEST';
export const LOGIN_ACTION_DONE = 'LOGIN_ACTION_DONE';
export const LOGIN_ACTION_RESET = 'LOGIN_ACTION_RESET';
