export const REGISTER_DEVICE_RESET = 'REGISTER_DEVICE_RESET';
export const REGISTER_DEVICE_REQUEST = 'REGISTER_DEVICE_REQUEST';
export const REGISTER_DEVICE_SUCCESS = 'REGISTER_DEVICE_SUCCESS';
export const REGISTER_DEVICE_ERROR = 'REGISTER_DEVICE_ERROR';
