export const USERS_FETCH_RESET = 'USERS_FETCH_RESET';
export const USERS_FETCH_REQUEST = 'USERS_FETCH_REQUEST';
export const USERS_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS';
export const USERS_FETCH_ERROR = 'USERS_FETCH_ERROR';
export const USERS_FETCH_RESET_DATA = 'USERS_FETCH_RESET_DATA';

export const FRIENDS_FETCH_RESET = 'FRIENDS_FETCH_RESET';
export const FRIENDS_FETCH_REQUEST = 'FRIENDS_FETCH_REQUEST';
export const FRIENDS_FETCH_SUCCESS = 'FRIENDS_FETCH_SUCCESS';
export const FRIENDS_FETCH_ERROR = 'FRIENDS_FETCH_ERROR';


export const FRIENDS_SEARCH_SUCCESS = 'FRIENDS_SEARCH_SUCCESS';

export const FRIEND_REQUEST_RESET = 'FRIEND_REQUEST_RESET';
export const FRIEND_REQUEST_REQUEST = 'FRIEND_REQUEST_REQUEST';
export const FRIEND_REQUEST_SUCCESS = 'FRIEND_REQUEST_SUCCESS';
export const FRIEND_REQUEST_ERROR = 'FRIEND_REQUEST_ERROR';

export const FRIEND_GET_REQUESTS_RESET = 'FRIEND_GET_REQUESTS_RESET';
export const FRIEND_GET_REQUESTS_REQUEST = 'FRIEND_GET_REQUESTS_REQUEST';
export const FRIEND_GET_REQUESTS_SUCCESS = 'FRIEND_GET_REQUESTS_SUCCESS';
export const FRIEND_GET_REQUESTS_ERROR = 'FRIEND_GET_REQUESTS_ERROR';


export const FRIEND_ACCEPT_RESET = 'FRIEND_ACCEPT_RESET';
export const FRIEND_ACCEPT_REQUEST = 'FRIEND_ACCEPT_REQUEST';
export const FRIEND_ACCEPT_SUCCESS = 'FRIEND_ACCEPT_SUCCESS';
export const FRIEND_ACCEPT_ERROR = 'FRIEND_ACCEPT_ERROR';


export const FRIEND_REJECT_RESET = 'FRIEND_REJECT_RESET';
export const FRIEND_REJECT_REQUEST = 'FRIEND_REJECT_REQUEST';
export const FRIEND_REJECT_SUCCESS = 'FRIEND_REJECT_SUCCESS';
export const FRIEND_REJECT_ERROR = 'FRIEND_REJECT_ERROR';
