export const GROUP_FETCH_RESET = 'GROUP_FETCH_RESET';
export const GROUP_FETCH_REQUEST = 'GROUP_FETCH_REQUEST';
export const GROUP_FETCH_SUCCESS = 'GROUP_FETCH_SUCCESS';
export const GROUP_FETCH_ERROR = 'GROUP_FETCH_ERROR';

export const GROUP_ADD_REQUEST = 'GROUP_ADD_REQUEST';
export const GROUP_ADD_SUCCESS = 'GROUP_ADD_SUCCESS';
export const GROUP_ADD_ERROR = 'GROUP_ADD_ERROR';
export const GROUP_ADD_RESET = 'GROUP_ADD_RESET';

export const GROUP_REMOVE_TAG_REQUEST = 'GROUP_REMOVE_TAG_REQUEST';
export const GROUP_REMOVE_TAG_SUCCESS = 'GROUP_REMOVE_TAG_SUCCESS';
export const GROUP_REMOVE_TAG_ERROR = 'GROUP_REMOVE_TAG_ERROR';
export const GROUP_REMOVE_TAG_RESET = 'GROUP_REMOVE_TAG_RESET';

export const GROUP_REMOVE_GROUP_REQUEST = 'GROUP_REMOVE_GROUP_REQUEST';
export const GROUP_REMOVE_GROUP_SUCCESS = 'GROUP_REMOVE_GROUP_SUCCESS';
export const GROUP_REMOVE_GROUP_ERROR = 'GROUP_REMOVE_GROUP_ERROR';
export const GROUP_REMOVE_GROUP_RESET = 'GROUP_REMOVE_GROUP_RESET';


export const GROUP_GROUP_ADD_REQUEST = 'GROUP_GROUP_ADD_REQUEST';
export const GROUP_GROUP_ADD_SUCCESS = 'GROUP_GROUP_ADD_SUCCESS';
export const GROUP_GROUP_ADD_ERROR = 'GROUP_GROUP_ADD_ERROR';
export const GROUP_GROUP_ADD_RESET = 'GROUP_GROUP_ADD_RESET';

export const ONLYGROUPS_FETCH_RESET = 'ONLYGROUPS_FETCH_RESET';
export const ONLYGROUPS_FETCH_REQUEST = 'ONLYGROUPS_FETCH_REQUEST';
export const ONLYGROUPS_FETCH_SUCCESS = 'ONLYGROUPS_FETCH_SUCCESS';
export const ONLYGROUPS_FETCH_ERROR = 'ONLYGROUPS_FETCH_ERROR';
