export const MY_ACTIVITIES_FETCH_RESET = 'MY_ACTIVITIES_FETCH_RESET';
export const MY_ACTIVITIES_FETCH_REQUEST = 'MY_ACTIVITIES_FETCH_REQUEST';
export const MY_ACTIVITIES_FETCH_SUCCESS = 'MY_ACTIVITIES_FETCH_SUCCESS';
export const MY_ACTIVITIES_FETCH_ERROR = 'MY_ACTIVITIES_FETCH_ERROR';

export const MY_ACTIVITY_ADD_REQUEST = 'MY_ACTIVITY_ADD_REQUEST';
export const MY_ACTIVITY_ADD_SUCCESS = 'MY_ACTIVITY_ADD_SUCCESS';
export const MY_ACTIVITY_ADD_ERROR = 'MY_ACTIVITY_ADD_ERROR';
export const MY_ACTIVITY_ADD_RESET = 'MY_ACTIVITY_ADD_RESET';

export const MY_ACTIVITY_REMOVE_TAG_REQUEST = 'MY_ACTIVITY_REMOVE_TAG_REQUEST';
export const MY_ACTIVITY_REMOVE_TAG_SUCCESS = 'MY_ACTIVITY_REMOVE_TAG_SUCCESS';
export const MY_ACTIVITY_REMOVE_TAG_ERROR = 'MY_ACTIVITY_REMOVE_TAG_ERROR';
export const MY_ACTIVITY_REMOVE_TAG_RESET = 'MY_ACTIVITY_REMOVE_TAG_RESET';

export const MY_ACTIVITY_REMOVE_GROUP_REQUEST = 'MY_ACTIVITY_REMOVE_GROUP_REQUEST';
export const MY_ACTIVITY_REMOVE_GROUP_SUCCESS = 'MY_ACTIVITY_REMOVE_GROUP_SUCCESS';
export const MY_ACTIVITY_REMOVE_GROUP_ERROR = 'MY_ACTIVITY_REMOVE_GROUP_ERROR';
export const MY_ACTIVITY_REMOVE_GROUP_RESET = 'MY_ACTIVITY_REMOVE_GROUP_RESET';


export const MY_ACTIVITY_GROUP_ADD_REQUEST = 'MY_ACTIVITY_GROUP_ADD_REQUEST';
export const MY_ACTIVITY_GROUP_ADD_SUCCESS = 'MY_ACTIVITY_GROUP_ADD_SUCCESS';
export const MY_ACTIVITY_GROUP_ADD_ERROR = 'MY_ACTIVITY_GROUP_ADD_ERROR';
export const MY_ACTIVITY_GROUP_ADD_RESET = 'MY_ACTIVITY_GROUP_ADD_RESET';
