export const OFFLINE_REQUEST = 'OFFLINE_REQUEST';
export const OFFLINE_DONE = 'OFFLINE_DONE';
export const OFFLINE_CLEAR = 'OFFLINE_CLEAR';
export const OFFLINE_QUEUE = 'OFFLINE_QUEUE';
export const OFFLINE_ERROR = 'OFFLINE_ERROR';
export const OFFLINE_RESET = 'OFFLINE_RESET';
