export const SHARE_ADD_RESET = 'SHARE_ADD_RESET';
export const SHARE_ADD_REQUEST = 'SHARE_ADD_REQUEST';
export const SHARE_ADD_SUCCESS = 'SHARE_ADD_SUCCESS';
export const SHARE_ADD_ERROR = 'SHARE_ADD_ERROR';

export const SHARE_REMOVE_RESET = 'SHARE_REMOVE_RESET';
export const SHARE_REMOVE_REQUEST = 'SHARE_REMOVE_REQUEST';
export const SHARE_REMOVE_SUCCESS = 'SHARE_REMOVE_SUCCESS';
export const SHARE_REMOVE_ERROR = 'SHARE_REMOVE_ERROR';


export const SHARES_FETCH_RESET = 'SHARES_FETCH_RESET';
export const SHARES_FETCH_REQUEST = 'SHARES_FETCH_REQUEST';
export const SHARES_FETCH_SUCCESS = 'SHARES_FETCH_SUCCESS';
export const SHARES_FETCH_ERROR = 'SHARES_FETCH_ERROR';

export const UPDATE_SHARE_COUNT = 'UPDATE_SHARE_COUNT';
