export const STATS_FETCH_RESET = 'STATS_FETCH_RESET';
export const STATS_FETCH_REQUEST = 'STATS_FETCH_REQUEST';
export const STATS_FETCH_SUCCESS = 'STATS_FETCH_SUCCESS';
export const STATS_FETCH_ERROR = 'STATS_FETCH_ERROR';
