export const SUBSCRIBE_RESET = 'SUBSCRIBE_RESET';
export const SUBSCRIBE_REQUEST = 'SUBSCRIBE_REQUEST';
export const SUBSCRIBE_SUCCESS = 'SUBSCRIBE_SUCCESS';
export const SUBSCRIBE_ERROR = 'SUBSCRIBE_ERROR';

export const UNSUBSCRIBE_RESET = 'UNSUBSCRIBE_RESET';
export const UNSUBSCRIBE_REQUEST = 'UNSUBSCRIBE_REQUEST';
export const UNSUBSCRIBE_SUCCESS = 'UNSUBSCRIBE_SUCCESS';
export const UNSUBSCRIBE_ERROR = 'UNSUBSCRIBE_ERROR';


export const SUBSCRIBERS_FETCH_RESET = 'SUBSCRIBERS_FETCH_RESET';
export const SUBSCRIBERS_FETCH_REQUEST = 'SUBSCRIBERS_FETCH_REQUEST';
export const SUBSCRIBERS_FETCH_SUCCESS = 'SUBSCRIBERS_FETCH_SUCCESS';
export const SUBSCRIBERS_FETCH_ERROR = 'SUBSCRIBERS_FETCH_ERROR';
