export const TAGS_FETCH_RESET = 'TAGS_FETCH_RESET';
export const TAGS_FETCH_REQUEST = 'TAGS_FETCH_REQUEST';
export const TAGS_FETCH_SUCCESS = 'TAGS_FETCH_SUCCESS';
export const TAGS_FETCH_ERROR = 'TAGS_FETCH_ERROR';

export const TAGS_SEARCH_SUCCESS = 'TAGS_SEARCH_SUCCESS';

export const TAG_ADD_RESET = 'TAG_ADD_RESET';
export const TAG_ADD_REQUEST = 'TAG_ADD_REQUEST';
export const TAG_ADD_SUCCESS = 'TAG_ADD_SUCCESS';
export const TAG_ADD_ERROR = 'TAG_ADD_ERROR';


export const TAG_UPDATE_RESET = 'TAG_UPDATE_RESET';
export const TAG_UPDATE_REQUEST = 'TAG_UPDATE_REQUEST';
export const TAG_UPDATE_SUCCESS = 'TAG_UPDATE_SUCCESS';
export const TAG_UPDATE_ERROR = 'TAG_UPDATE_ERROR';


export const TAG_DELETE_RESET = 'TAG_DELETE_RESET';
export const TAG_DELETE_REQUEST = 'TAG_DELETE_REQUEST';
export const TAG_DELETE_SUCCESS = 'TAG_DELETE_SUCCESS';
export const TAG_DELETE_ERROR = 'TAG_DELETE_ERROR';
