export const TIME_TOGGLE_REQUEST = 'TIME_TOGGLE_REQUEST';
export const TIME_TOGGLE_SUCCESS = 'TIME_TOGGLE_SUCCESS';
export const TIME_TOGGLE_ERROR = 'TIME_TOGGLE_ERROR';
export const TIME_TOGGLE_RESET = 'TIME_TOGGLE_RESET';

export const TIME_FETCH_BY_GROUP_REQUEST = 'TIME_FETCH_BY_GROUP_REQUEST';
export const TIME_FETCH_BY_GROUP_SUCCESS = 'TIME_FETCH_BY_GROUP_SUCCESS';
export const TIME_FETCH_BY_GROUP_ERROR = 'TIME_FETCH_BY_GROUP_ERROR';
export const TIME_FETCH_BY_GROUP_RESET = 'TIME_FETCH_BY_GROUP_RESET';

export const TIME_CREATE_REQUEST = 'TIME_CREATE_REQUEST';
export const TIME_CREATE_SUCCESS = 'TIME_CREATE_SUCCESS';
export const TIME_CREATE_ERROR = 'TIME_CREATE_ERROR';
export const TIME_CREATE_RESET = 'TIME_CREATE_RESET';

export const TIME_UPDATE_REQUEST = 'TIME_UPDATE_REQUEST';
export const TIME_UPDATE_SUCCESS = 'TIME_UPDATE_SUCCESS';
export const TIME_UPDATE_ERROR = 'TIME_UPDATE_ERROR';
export const TIME_UPDATE_RESET = 'TIME_UPDATE_RESET';

export const TIME_DELETE_REQUEST = 'TIME_DELETE_REQUEST';
export const TIME_DELETE_SUCCESS = 'TIME_DELETE_SUCCESS';
export const TIME_DELETE_ERROR = 'TIME_DELETE_ERROR';
export const TIME_DELETE_RESET = 'TIME_DELETE_RESET';
