export const TIME_TOGGLE_REQUEST = 'TIME_TOGGLE_REQUEST';
export const TIME_TOGGLE_SUCCESS = 'TIME_TOGGLE_SUCCESS';
export const TIME_TOGGLE_ERROR = 'TIME_TOGGLE_ERROR';
export const TIME_TOGGLE_RESET = 'TIME_TOGGLE_RESET';
