export const TIME_TOGGLE_REQUEST = 'TIME_TOGGLE_REQUEST';
export const TIME_TOGGLE_SUCCESS = 'TIME_TOGGLE_SUCCESS';
export const TIME_TOGGLE_ERROR = 'TIME_TOGGLE_ERROR';
export const TIME_TOGGLE_RESET = 'TIME_TOGGLE_RESET';

export const TIME_FETCH_REQUEST = 'TIME_FETCH_REQUEST';
export const TIME_FETCH_SUCCESS = 'TIME_FETCH_SUCCESS';
export const TIME_FETCH_ERROR = 'TIME_FETCH_ERROR';
export const TIME_FETCH_RESET = 'TIME_FETCH_RESET';
